services:
    db:
        image: postgres:13-alpine
        container_name: ${DOCKER_NAME}-db
        restart: unless-stopped
        volumes:
            - ./docker/postgres/init:/docker-entrypoint-initdb.d
            - ./docker/postgres/data/:/var/lib/postgresql/data/
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        networks:
            - main

    laravel:
        build:
            args:
                user: ${USER}
                uid: ${UID}
            context: ./docker/php/
            dockerfile: Dockerfile
        image: laravel
        container_name: ${DOCKER_NAME}-laravel
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./app/:/var/www
            - ./docker/php/conf/:/usr/local/etc/php
        networks:
            - main
        depends_on:
            - db

    nginx:
        image: nginx:1.17-alpine
        container_name: ${DOCKER_NAME}-nginx
        restart: unless-stopped
        ports:
            - ${NGINX_PORT}:80
            - ${NGINX_SSL_PORT}:443
        volumes:
            - ./app/:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
            - ./docker/certificates:/certificates
        networks:
            - main
        depends_on:
            - laravel

networks:
    main:
        driver: bridge
        name: ${DOCKER_NETWORK_NAME}
